---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cx-ingress-web
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    {{- if .Values.web.domainName }}
    - host: {{ .Values.web.domainName }}
      http:
    {{- else }}
    - http:
    {{- end }}
        paths:
          - backend:
              serviceName: cx-web-svc
              servicePort: 80

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cx-ingress-api
  annotations:
    {{- if (eq "quay.io" .Values.ingressType) }}
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    {{- else }}
    nginx.ingress.kubernetes.io/rewrite-target: /
    {{- end }}
spec:
  rules:
    {{- if .Values.web.domainName }}
    - host: {{ .Values.web.domainName }}
      http:
    {{- else }}
    - http:
    {{- end }}
        paths:
          {{- if (eq "quay.io" .Values.ingressType) }}
          - path: /comm-api/?(.*)
          {{- else }}
          - path: /comm-api
          {{- end }}
            backend:
              serviceName: cx-comm-svc
              servicePort: 8081
          {{- if (eq "quay.io" .Values.ingressType) }}
          - path: /iaas-api/?(.*)
          {{- else }}
          - path: /iaas-api
          {{- end }}
            backend:
              serviceName: cx-iaas-svc
              servicePort: 8082
          {{- if (eq "quay.io" .Values.ingressType) }}
          - path: /monit-api/?(.*)
          {{- else }}
          - path: /monit-api
          {{- end }}
            backend:
              serviceName: cx-monit-svc
              servicePort: {{ default 9000 .Values.monit.apiPort }}

---

{{- if .Values.fabric.enabled }}

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cx-ingress-fabric-index-html
  annotations:
    {{- if (eq "https" .Values.fabric.protocol) }}
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    {{- end }}
    nginx.ingress.kubernetes.io/rewrite-target: /index.html
spec:
  rules:
    {{- if .Values.web.domainName }}
    - host: {{ .Values.web.domainName }}
      http:
    {{- else }}
    - http:
    {{- end }}
        paths:
          - path: /attoFabric.html
            backend:
              serviceName: cx-fabric-svc
              servicePort: {{ default 8080 .Values.fabric.apiPort }}

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cx-ingress-fabric-core-js
  annotations:
    {{- if (eq "https" .Values.fabric.protocol) }}
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    {{- end }}
    nginx.ingress.kubernetes.io/rewrite-target: /core.js
spec:
  rules:
    {{- if .Values.web.domainName }}
    - host: {{ .Values.web.domainName }}
      http:
    {{- else }}
    - http:
    {{- end }}
        paths:
          - path: /core.js
            backend:
              serviceName: cx-fabric-svc
              servicePort: {{ default 8080 .Values.fabric.apiPort }}

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cx-ingress-fabric-main-css
  annotations:
    {{- if (eq "https" .Values.fabric.protocol) }}
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    {{- end }}
    nginx.ingress.kubernetes.io/rewrite-target: /css/main.css
spec:
  rules:
    {{- if .Values.web.domainName }}
    - host: {{ .Values.web.domainName }}
      http:
    {{- else }}
    - http:
    {{- end }}
        paths:
          - path: /css/fabricMain.css
            backend:
              serviceName: cx-fabric-svc
              servicePort: {{ default 8080 .Values.fabric.apiPort }}

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cx-ingress-fabric-favicon-ico
  annotations:
    {{- if (eq "https" .Values.fabric.protocol) }}
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    {{- end }}
    nginx.ingress.kubernetes.io/rewrite-target: /favicon.ico
spec:
  rules:
    {{- if .Values.web.domainName }}
    - host: {{ .Values.web.domainName }}
      http:
    {{- else }}
    - http:
    {{- end }}
        paths:
          - path: /favicon.ico
            backend:
              serviceName: cx-fabric-svc
              servicePort: {{ default 8080 .Values.fabric.apiPort }}

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cx-ingress-fabric
  annotations:
    {{- if (eq "https" .Values.fabric.protocol) }}
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    {{- end }}
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    {{- if .Values.web.domainName }}
    - host: {{ .Values.web.domainName }}
      http:
    {{- else }}
    - http:
    {{- end }}
        paths:
          - path: /app
            backend:
              serviceName: cx-fabric-svc
              servicePort: {{ default 8080 .Values.fabric.apiPort }}
          - path: /css/svg
            backend:
              serviceName: cx-fabric-svc
              servicePort: {{ default 8080 .Values.fabric.apiPort }}
          - path: /lib
            backend:
              serviceName: cx-fabric-svc
              servicePort: {{ default 8080 .Values.fabric.apiPort }}
          - path: /svg
            backend:
              serviceName: cx-fabric-svc
              servicePort: {{ default 8080 .Values.fabric.apiPort }}
          - path: /util
            backend:
              serviceName: cx-fabric-svc
              servicePort: {{ default 8080 .Values.fabric.apiPort }}
          - path: /obelle-fabric
            backend:
              serviceName: cx-fabric-svc
              servicePort: {{ default 8080 .Values.fabric.apiPort }}
          - path: /favicon.ico
            backend:
              serviceName: cx-fabric-svc
              servicePort: {{ default 8080 .Values.fabric.apiPort }}

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cx-ingress-fabric-ws
  annotations:
    {{- if (eq "https" .Values.fabric.protocol) }}
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    {{- end }}
    nginx.org/websocket-services: cx-fabric-svc
spec:
  rules:
    {{- if .Values.web.domainName }}
    - host: {{ .Values.web.domainName }}
      http:
    {{- else }}
    - http:
    {{- end }}
        paths:
          - path: /fabric/ws
            backend:
              serviceName: cx-fabric-svc
              servicePort: {{ default 8080 .Values.fabric.apiPort }}

---

{{- end }}
